standard std::exception constructor does not know a string parameter
used std::runtime_error instead, which reflects better the kind of
error: errors that are due to events beyond the scope of the program and
can not be easily predicted